#+title: Setting up a Conda environment for the UU ML course

* Introduction
This directory provides the information needed to setup your Conda environment on the Nikhef cluster and get
started.  Some introductory notes on the use of bash (command-line/shell), emacs (text editing), (Python and)
git can be found in [[file:GettingStartedWithBashEmacsPythonAndGit.pdf]].

We will use [[https://docs.conda.io/][Conda]],an open-source package- and environment-management system, to setup an environment for our
machine-learning course with the required packages.  Follow the steps below to install Conda and setup an
environment. 

* Installing Conda
If you haven't installed Conda in your account on this cluster before, you should do it now.  In order to do
so, you can download the following bash script, make it executable, and run it:
#+begin_src bash
  wget https://raw.githubusercontent.com/MarcvdSluys/UU-ML-Cluster/master/install-conda.sh
  chmod u+x install-conda.sh
  ./install-conda.sh
#+end_src
This takes about 5 minutes and will install Conda in ~/data/gravwav/$USER/.conda/~.  Note that the installer
changes your settings in =~/.bashrc=.

* Creating a Conda environment for the machine-learning course
You will have to use a fresh bash shell to do this.  You can either logout and login again, or type
#+begin_src bash
  bash
#+end_src
(When using the latter option, you will have to type ~exit~ twice to logout from the cluster.)

Then download the configuration file and setup the Conda environment for the ML course:
#+begin_src bash
  wget https://raw.githubusercontent.com/MarcvdSluys/UU-ML-Cluster/master/ml_course.yml
  conda env create -f ml_course.yml
#+end_src
This can take about 15 minutes.

If all went well, you should see the instructions to activate and deactivate the ~ml_course~ Conda environment:
#+begin_src bash
  conda activate ml_course
  conda deactivate
#+end_src
